[package]
name = "orderbook_modules"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-tungstenite = "0.30.0"
thiserror = "2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "orderbook_benchmark"
harness = false

